apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedspy
  labels:
    app: speedspy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedspy
  template:
    metadata:
      labels:
        app: speedspy
    spec:
      containers:
        - name: speedspy
          image: vauhtijuoksu.azurecr.io/vauhtijuoksu/speedspy:dev
          imagePullPolicy: Always
          volumeMounts:
            - name: bot-configs
              mountPath: /app
              subPath: .env
            - name: runner-database
              mountPath: /app/database
      volumes:
        - name: bot-configs
          configMap:
            name: speedspy-config
        - name: runner-database
          hostPath:
            path: speedrunners.db